server:
  port: 8085
  
spring:
  application:
    name: API-GATEWAY 
    
    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/api/v1/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/api/v1/hotels/** 
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/api/v1/ratings/**   
         
  config:
    import: optional:configserver:http://localhost:8086  
     
okta:
  oauth2:
    issuer: https://dev-13111056.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8a3ganb6ySnTws5d7
    client-secret: -SDZl02GauzKvK3a5mDqEUsb2mQtKggZi0r_F_4K
    scopes: openid, profile, email, offline_access  